### ISSUE TITLE
Wi-Fi Consent Page entwickeln

### ISSUE THREAD

**Issue by VitaliaSvirskaja** [TSC-Rot-Gold-Casino-Nurnberg-e-V/rgc-wifi-consent#1]
### Zu klären
- [x] Welche Informationen bzw. Elemente sollen auf der Page dargestellt werden?
- [x] Wie soll das Design ungefähr aussehen? (Gibt es vielleicht eine Vorlage?)
- [x] Welche rechtlichen Regelungen müssen berücksichtigt werden bzw. wo kann man sich einlesen?

### TODOs
- [x] Nach gesetzeskonformen Templates bzw. Konfiguratoren suchen
- [ ] gleiche Schriftart wie Webseite verwenden
- [x] Hintergrundfarbe (weiß) des Dialogs sollte base-50 sein
- [x] Höhe des Dialogs bei responsive
- [x] Abstand zwischen Headline und Text auf der Willkommen-Seite vergrößern

### Technische Dokumentation
https://docs.netgate.com/pfsense/en/latest/captiveportal/configuration.html#captive-portal-login-page

```HTML
<html>
<head>
	<title>Welcome to our portal</title>
</head>
<body>
	<p>Welcome to our portal</p>
	<p>Click Continue to access the Internet</p>
	<form method="post" action="$PORTAL_ACTION$">
		<input name="redirurl" type="hidden" value="$PORTAL_REDIRURL$">
		<input name="zone" type="hidden" value="$PORTAL_ZONE$">
		<input name="accept" type="submit" value="Continue">
	</form>
</body>
</html>
```

### Webseiten für Recherche
- https://www.datenschutzexperte.de/blog/datenschutz-im-alltag/wlan-hotspots-rechtliches/
- https://www.bmwk.de/Redaktion/DE/Artikel/Service/entwurf-telemediengesetz-drei.html
- https://www.datenschutzexperte.de/eu-dsgvo/

**Comment by DanielMerkl** [comment]
Schriftart wird bei Bedarf angepasst
